VERSION = { 1 }
SETUP_UPDATE_EVERY_CYCLE = { FALSE }
SETUP_UPDATE_WHEN_HALTED = { TRUE }
SETUP_BUFFER_SIZE = { 1000000 }
ANALOG_PIN = { CCP9 } 
ANALOG_PIN = { RB2 } 
ANALOG_PIN = { RB3 } 
ANALOG_PIN = { RD4 } 
